using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using AiBenchmark.Net.Assertions;
using AiBenchmark.Net.Models;

namespace AiBenchmark.Net.Benchmarking;

/// <summary>
/// Result of an executed AI benchmark invocation with comprehensive assertion capabilities.
/// </summary>
public sealed class AiBenchmarkResult
{
    private readonly List<AssertionResult> _assertions = new();

    /// <summary>Benchmark test name or scenario label.</summary>
    public string Name { get; }

    /// <summary>The underlying telemetry report.</summary>
    public AiBenchmarkReport Report { get; private set; }

    /// <summary>Prompt text tested.</summary>
    public string? Prompt => Report.Prompt;

    /// <summary>Text generated by the model.</summary>
    public string? ResponseText => Report.ResponseText;

    /// <summary>Target model ID.</summary>
    public string ModelId => Report.ModelId;

    /// <summary>AI provider.</summary>
    public string Provider => Report.Provider;

    /// <summary>Total duration.</summary>
    public TimeSpan Duration => Report.Duration;

    /// <summary>Total duration in milliseconds.</summary>
    public double DurationMs => Report.DurationMs;

    /// <summary>Streaming Time-To-First-Token in milliseconds (if streaming).</summary>
    public double? TimeToFirstTokenMs => Report.TimeToFirstTokenMs;

    /// <summary>Total tokens consumed.</summary>
    public long TotalTokens => Report.TotalTokens;

    /// <summary>Input / prompt tokens.</summary>
    public long InputTokens => Report.InputTokens;

    /// <summary>Output / completion tokens.</summary>
    public long OutputTokens => Report.OutputTokens;

    /// <summary>Cached input tokens.</summary>
    public long CachedInputTokens => Report.CachedInputTokens;

    /// <summary>Reasoning tokens.</summary>
    public long ReasoningTokens => Report.ReasoningTokens;

    /// <summary>Calculated USD cost.</summary>
    public decimal EstimatedCostUsd => Report.EstimatedCostUsd;

    /// <summary>Whether invocation was streamed.</summary>
    public bool IsStreaming => Report.IsStreaming;

    /// <summary>Whether invocation succeeded.</summary>
    public bool Success => Report.Success;

    /// <summary>Tools called during execution.</summary>
    public IReadOnlyList<ToolInvocationRecord> ToolInvocations => Report.ToolInvocations;

    /// <summary>MCP interactions.</summary>
    public IReadOnlyList<McpInvocationRecord> McpInvocations => Report.McpInvocations;

    /// <summary>Subagent delegations.</summary>
    public IReadOnlyList<SubagentInvocationRecord> SubagentInvocations => Report.SubagentInvocations;

    /// <summary>List of assertions evaluated for this benchmark.</summary>
    public IReadOnlyList<AssertionResult> Assertions => _assertions;

    /// <summary>True if all evaluated assertions passed.</summary>
    public bool AllAssertionsPassed => _assertions.All(a => a.Passed);

    /// <summary>
    /// Initializes a new instance of <see cref="AiBenchmarkResult"/>.
    /// </summary>
    public AiBenchmarkResult(string name, AiBenchmarkReport report)
    {
        Name = name;
        Report = report;
    }

    private AiBenchmarkResult RecordAndValidate(AssertionResult result, bool shouldThrow = true)
    {
        _assertions.Add(result);
        Report = Report with { Assertions = _assertions.ToList() };

        if (!result.Passed && shouldThrow)
        {
            throw new AiAssertionException(result, Report);
        }

        return this;
    }

    #region Cost & Performance Assertions

    /// <summary>Asserts that the estimated cost does not exceed the budget.</summary>
    public AiBenchmarkResult AssertCost(decimal maxCostUsd)
    {
        bool ok = EstimatedCostUsd <= maxCostUsd;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Cost", $"Cost <= ${maxCostUsd:F6}", $"${EstimatedCostUsd:F6}")
            : AssertionResult.Fail("Cost", $"Cost <= ${maxCostUsd:F6}", $"${maxCostUsd:F6}", $"${EstimatedCostUsd:F6}",
                $"Cost budget exceeded! Observed ${EstimatedCostUsd:F6}, budget is ${maxCostUsd:F6}."));
    }

    /// <summary>Asserts that the total duration does not exceed the threshold in milliseconds.</summary>
    public AiBenchmarkResult AssertDuration(double maxDurationMs)
    {
        bool ok = DurationMs <= maxDurationMs;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Latency", $"Duration <= {maxDurationMs:F0}ms", $"{DurationMs:F1}ms")
            : AssertionResult.Fail("Latency", $"Duration <= {maxDurationMs:F0}ms", $"{maxDurationMs:F0}ms", $"{DurationMs:F1}ms",
                $"Latency SLA breached! Observed {DurationMs:F1}ms, max allowed is {maxDurationMs:F0}ms."));
    }

    /// <summary>Asserts that the Time-To-First-Token does not exceed the threshold in milliseconds.</summary>
    public AiBenchmarkResult AssertTimeToFirstToken(double maxTtftMs)
    {
        if (!TimeToFirstTokenMs.HasValue)
        {
            return RecordAndValidate(AssertionResult.Fail("Latency", $"TTFT <= {maxTtftMs:F0}ms", $"{maxTtftMs:F0}ms", "N/A",
                "Invocation did not capture Time-To-First-Token (not streamed or no chunks received)."));
        }

        bool ok = TimeToFirstTokenMs.Value <= maxTtftMs;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Latency", $"TTFT <= {maxTtftMs:F0}ms", $"{TimeToFirstTokenMs.Value:F1}ms")
            : AssertionResult.Fail("Latency", $"TTFT <= {maxTtftMs:F0}ms", $"{maxTtftMs:F0}ms", $"{TimeToFirstTokenMs.Value:F1}ms",
                $"Streaming TTFT SLA breached! Observed {TimeToFirstTokenMs.Value:F1}ms, max allowed is {maxTtftMs:F0}ms."));
    }

    /// <summary>Asserts bounds on token consumption.</summary>
    public AiBenchmarkResult AssertTokens(long? maxInput = null, long? maxOutput = null, long? maxTotal = null)
    {
        if (maxInput.HasValue && InputTokens > maxInput.Value)
        {
            return RecordAndValidate(AssertionResult.Fail("Tokens", $"InputTokens <= {maxInput.Value}", $"{maxInput.Value}", $"{InputTokens}",
                $"Input token count exceeded: observed {InputTokens}, max allowed is {maxInput.Value}."));
        }

        if (maxOutput.HasValue && OutputTokens > maxOutput.Value)
        {
            return RecordAndValidate(AssertionResult.Fail("Tokens", $"OutputTokens <= {maxOutput.Value}", $"{maxOutput.Value}", $"{OutputTokens}",
                $"Output token count exceeded: observed {OutputTokens}, max allowed is {maxOutput.Value}."));
        }

        if (maxTotal.HasValue && TotalTokens > maxTotal.Value)
        {
            return RecordAndValidate(AssertionResult.Fail("Tokens", $"TotalTokens <= {maxTotal.Value}", $"{maxTotal.Value}", $"{TotalTokens}",
                $"Total token count exceeded: observed {TotalTokens}, max allowed is {maxTotal.Value}."));
        }

        return RecordAndValidate(AssertionResult.Pass("Tokens", "Token Bounds", $"In={InputTokens}, Out={OutputTokens}, Total={TotalTokens}"));
    }

    /// <summary>Asserts that prompt cache hit rate meets or exceeds the required threshold.</summary>
    public AiBenchmarkResult AssertPromptCacheRate(double minHitRate)
    {
        double actualRate = InputTokens > 0 ? (double)CachedInputTokens / InputTokens : 0;
        bool ok = actualRate >= minHitRate;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("PromptCache", $"CacheHitRate >= {minHitRate:P0}", $"{actualRate:P1}")
            : AssertionResult.Fail("PromptCache", $"CacheHitRate >= {minHitRate:P0}", $"{minHitRate:P0}", $"{actualRate:P1}",
                $"Prompt caching hit rate below threshold! Observed {actualRate:P1}, expected at least {minHitRate:P0}."));
    }

    #endregion

    #region Response Content Assertions

    /// <summary>Asserts that the response text contains the expected substring.</summary>
    public AiBenchmarkResult AssertResponseContains(string expectedSubstring, StringComparison comparison = StringComparison.OrdinalIgnoreCase)
    {
        string text = ResponseText ?? string.Empty;
        bool ok = text.AsSpan().Contains(expectedSubstring.AsSpan(), comparison);
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Response", $"Contains '{expectedSubstring}'", "Found")
            : AssertionResult.Fail("Response", $"Contains '{expectedSubstring}'", expectedSubstring, text.Length > 80 ? text[..80] + "..." : text,
                $"Response does not contain expected text '{expectedSubstring}'."));
    }

    /// <summary>Asserts that the response text matches a regular expression.</summary>
    public AiBenchmarkResult AssertResponseMatches(string regexPattern, RegexOptions options = RegexOptions.None)
    {
        string text = ResponseText ?? string.Empty;
        bool ok = Regex.IsMatch(text, regexPattern, options);
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Response", $"Matches '{regexPattern}'", "Matched")
            : AssertionResult.Fail("Response", $"Matches '{regexPattern}'", regexPattern, text.Length > 80 ? text[..80] + "..." : text,
                $"Response does not match regular expression '{regexPattern}'."));
    }

    /// <summary>Asserts that the response text is valid JSON.</summary>
    public AiBenchmarkResult AssertValidJson()
    {
        string text = (ResponseText ?? string.Empty).Trim();
        if (text.StartsWith("```json", StringComparison.OrdinalIgnoreCase))
        {
            text = text.Substring(7).Trim();
            if (text.EndsWith("```")) text = text[..^3].Trim();
        }

        try
        {
            using var doc = JsonDocument.Parse(text);
            return RecordAndValidate(AssertionResult.Pass("Response", "Valid JSON", "Parsed Successfully"));
        }
        catch (JsonException ex)
        {
            return RecordAndValidate(AssertionResult.Fail("Response", "Valid JSON", "Valid JSON syntax", "Syntax Error",
                $"Response is not valid JSON: {ex.Message}"));
        }
    }

    /// <summary>Asserts character length of the response text.</summary>
    public AiBenchmarkResult AssertResponseLength(int? minChars = null, int? maxChars = null)
    {
        int length = (ResponseText ?? string.Empty).Length;
        if (minChars.HasValue && length < minChars.Value)
        {
            return RecordAndValidate(AssertionResult.Fail("Response", $"Length >= {minChars.Value}", $"{minChars.Value} chars", $"{length} chars",
                $"Response too short: {length} chars (minimum {minChars.Value})."));
        }

        if (maxChars.HasValue && length > maxChars.Value)
        {
            return RecordAndValidate(AssertionResult.Fail("Response", $"Length <= {maxChars.Value}", $"{maxChars.Value} chars", $"{length} chars",
                $"Response too long: {length} chars (maximum {maxChars.Value})."));
        }

        return RecordAndValidate(AssertionResult.Pass("Response", "Length Bounds", $"{length} chars"));
    }

    /// <summary>Custom predicate assertion on response text.</summary>
    public AiBenchmarkResult AssertResponse(Func<string, bool> predicate, string description = "Custom response condition")
    {
        ArgumentNullException.ThrowIfNull(predicate);
        string text = ResponseText ?? string.Empty;
        bool ok = predicate(text);
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Response", description, "Condition satisfied")
            : AssertionResult.Fail("Response", description, "True", "False", $"Custom condition failed: '{description}'."));
    }

    #endregion

    #region Tool & Function Calling Assertions

    /// <summary>Asserts that a specific tool or function was called.</summary>
    public AiBenchmarkResult AssertToolCalled(string toolName)
    {
        bool found = ToolInvocations.Any(t => string.Equals(t.ToolName, toolName, StringComparison.OrdinalIgnoreCase));
        return RecordAndValidate(found
            ? AssertionResult.Pass("Tool", $"Called '{toolName}'", "Invoked")
            : AssertionResult.Fail("Tool", $"Called '{toolName}'", toolName, string.Join(", ", ToolInvocations.Select(t => t.ToolName)),
                $"Tool '{toolName}' was not invoked. Observed calls: [{string.Join(", ", ToolInvocations.Select(t => t.ToolName))}]."));
    }

    /// <summary>Asserts total number of tool invocations.</summary>
    public AiBenchmarkResult AssertToolCallCount(int expectedCount)
    {
        bool ok = ToolInvocations.Count == expectedCount;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Tool", $"Tool Call Count == {expectedCount}", $"{ToolInvocations.Count}")
            : AssertionResult.Fail("Tool", $"Tool Call Count == {expectedCount}", $"{expectedCount}", $"{ToolInvocations.Count}",
                $"Expected {expectedCount} tool calls, but observed {ToolInvocations.Count}."));
    }

    /// <summary>Asserts tool arguments for a specific tool call.</summary>
    public AiBenchmarkResult AssertToolArguments(string toolName, Func<IReadOnlyDictionary<string, object?>, bool> predicate, string description = "Valid tool arguments")
    {
        var match = ToolInvocations.FirstOrDefault(t => string.Equals(t.ToolName, toolName, StringComparison.OrdinalIgnoreCase));
        if (match == null)
        {
            return RecordAndValidate(AssertionResult.Fail("Tool", $"Tool '{toolName}' Args", "Tool Invoked", "Tool Not Found",
                $"Cannot validate arguments because tool '{toolName}' was not called."));
        }

        bool ok = predicate(match.Arguments);
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Tool", $"Tool '{toolName}' {description}", "Arguments Valid")
            : AssertionResult.Fail("Tool", $"Tool '{toolName}' {description}", "True", "False",
                $"Tool '{toolName}' arguments did not satisfy condition: '{description}'."));
    }

    /// <summary>Asserts that no tools were called.</summary>
    public AiBenchmarkResult AssertNoToolsCalled()
    {
        bool ok = ToolInvocations.Count == 0;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Tool", "No Tools Called", "0 Tools")
            : AssertionResult.Fail("Tool", "No Tools Called", "0 Tools", $"{ToolInvocations.Count} Tools",
                $"Expected 0 tool calls, but observed: [{string.Join(", ", ToolInvocations.Select(t => t.ToolName))}]."));
    }

    #endregion

    #region Model Context Protocol (MCP) Assertions

    /// <summary>Asserts that an MCP tool was executed.</summary>
    public AiBenchmarkResult AssertMcpToolCalled(string server, string tool)
    {
        bool ok = McpInvocations.Any(m =>
            string.Equals(m.ServerName, server, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(m.ToolName, tool, StringComparison.OrdinalIgnoreCase));

        return RecordAndValidate(ok
            ? AssertionResult.Pass("MCP", $"MCP Tool '{server}.{tool}'", "Invoked")
            : AssertionResult.Fail("MCP", $"MCP Tool '{server}.{tool}'", $"{server}.{tool}", "Not Found",
                $"MCP tool '{server}.{tool}' was not invoked."));
    }

    /// <summary>Asserts that an MCP resource URI was accessed.</summary>
    public AiBenchmarkResult AssertMcpResourceAccessed(string resourceUri)
    {
        bool ok = McpInvocations.Any(m => string.Equals(m.ResourceUri, resourceUri, StringComparison.OrdinalIgnoreCase));
        return RecordAndValidate(ok
            ? AssertionResult.Pass("MCP", $"Resource '{resourceUri}'", "Accessed")
            : AssertionResult.Fail("MCP", $"Resource '{resourceUri}'", resourceUri, "Not Found",
                $"MCP resource '{resourceUri}' was not accessed."));
    }

    /// <summary>Asserts maximum interactions with a specific MCP server.</summary>
    public AiBenchmarkResult AssertMcpServerCount(string server, int maxCalls)
    {
        int count = McpInvocations.Count(m => string.Equals(m.ServerName, server, StringComparison.OrdinalIgnoreCase));
        bool ok = count <= maxCalls;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("MCP", $"MCP Server '{server}' Calls <= {maxCalls}", $"{count}")
            : AssertionResult.Fail("MCP", $"MCP Server '{server}' Calls <= {maxCalls}", $"{maxCalls}", $"{count}",
                $"MCP server '{server}' called {count} times (max allowed is {maxCalls})."));
    }

    #endregion

    #region Subagent Assertions

    /// <summary>Asserts that a subagent with the specified role was delegated to.</summary>
    public AiBenchmarkResult AssertSubagentInvoked(string agentRole)
    {
        bool ok = SubagentInvocations.Any(s => string.Equals(s.AgentRole, agentRole, StringComparison.OrdinalIgnoreCase));
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Subagent", $"Subagent '{agentRole}'", "Invoked")
            : AssertionResult.Fail("Subagent", $"Subagent '{agentRole}'", agentRole, "Not Found",
                $"Subagent with role '{agentRole}' was not delegated to."));
    }

    /// <summary>Asserts total subagent delegations count.</summary>
    public AiBenchmarkResult AssertSubagentCount(int expectedCount)
    {
        bool ok = SubagentInvocations.Count == expectedCount;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Subagent", $"Subagent Count == {expectedCount}", $"{SubagentInvocations.Count}")
            : AssertionResult.Fail("Subagent", $"Subagent Count == {expectedCount}", $"{expectedCount}", $"{SubagentInvocations.Count}",
                $"Expected {expectedCount} subagent delegations, but observed {SubagentInvocations.Count}."));
    }

    /// <summary>Asserts cost spend attributed to a specific subagent role.</summary>
    public AiBenchmarkResult AssertSubagentSpend(string agentRole, decimal maxCostUsd)
    {
        decimal spend = SubagentInvocations
            .Where(s => string.Equals(s.AgentRole, agentRole, StringComparison.OrdinalIgnoreCase))
            .Sum(s => s.CostUsd);

        bool ok = spend <= maxCostUsd;
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Subagent", $"Subagent '{agentRole}' Spend <= ${maxCostUsd:F6}", $"${spend:F6}")
            : AssertionResult.Fail("Subagent", $"Subagent '{agentRole}' Spend <= ${maxCostUsd:F6}", $"${maxCostUsd:F6}", $"${spend:F6}",
                $"Subagent '{agentRole}' exceeded budget! Spent ${spend:F6}, max allowed is ${maxCostUsd:F6}."));
    }

    /// <summary>Asserts that subagents executed in a specific sequential order.</summary>
    public AiBenchmarkResult AssertDelegationSequence(params string[] roles)
    {
        var actualRoles = SubagentInvocations.Select(s => s.AgentRole).ToList();
        string expectedStr = string.Join(" -> ", roles);
        string actualStr = string.Join(" -> ", actualRoles);

        bool ok = actualRoles.SequenceEqual(roles, StringComparer.OrdinalIgnoreCase);
        return RecordAndValidate(ok
            ? AssertionResult.Pass("Subagent", $"Sequence: {expectedStr}", actualStr)
            : AssertionResult.Fail("Subagent", $"Sequence: {expectedStr}", expectedStr, actualStr,
                $"Subagent sequence mismatch. Expected: [{expectedStr}], Observed: [{actualStr}]."));
    }

    #endregion
}
