using System;
using System.Collections.Generic;

namespace AiBenchmark.Net.Models;

/// <summary>
/// Detailed benchmark telemetry and SLA assertion report generated for an AI invocation.
/// </summary>
public sealed record AiBenchmarkReport
{
    /// <summary>
    /// The unique request or invocation identifier.
    /// </summary>
    public string RequestId { get; init; } = Guid.NewGuid().ToString("N");

    /// <summary>
    /// Gets the target AI model identifier.
    /// </summary>
    public string ModelId { get; init; } = string.Empty;

    /// <summary>
    /// Gets the provider or host (e.g. OpenAI, Anthropic, Google, Azure, Ollama).
    /// </summary>
    public string Provider { get; init; } = string.Empty;

    /// <summary>
    /// Gets the total execution duration.
    /// </summary>
    public TimeSpan Duration { get; init; }

    /// <summary>
    /// Gets the total execution duration in milliseconds.
    /// </summary>
    public double DurationMs => Duration.TotalMilliseconds;

    /// <summary>
    /// Gets the Time-To-First-Token latency for streaming responses.
    /// Null for non-streaming requests.
    /// </summary>
    public TimeSpan? TimeToFirstToken { get; init; }

    /// <summary>
    /// Gets the Time-To-First-Token latency in milliseconds.
    /// </summary>
    public double? TimeToFirstTokenMs => TimeToFirstToken?.TotalMilliseconds;

    /// <summary>
    /// Gets token usage breakdown.
    /// </summary>
    public TokenUsageSummary TokenUsage { get; init; } = TokenUsageSummary.Empty;

    /// <summary>
    /// Convenience shortcut for input tokens.
    /// </summary>
    public long InputTokens => TokenUsage.InputTokens;

    /// <summary>
    /// Convenience shortcut for output tokens.
    /// </summary>
    public long OutputTokens => TokenUsage.OutputTokens;

    /// <summary>
    /// Convenience shortcut for cached input tokens.
    /// </summary>
    public long CachedInputTokens => TokenUsage.CachedInputTokens;

    /// <summary>
    /// Convenience shortcut for total tokens.
    /// </summary>
    public long TotalTokens => TokenUsage.TotalTokens;

    /// <summary>
    /// Convenience shortcut for reasoning / thinking tokens.
    /// </summary>
    public long ReasoningTokens => TokenUsage.ReasoningTokens;

    /// <summary>
    /// Gets the calculated estimated cost in USD.
    /// </summary>
    public decimal EstimatedCostUsd { get; init; }

    /// <summary>
    /// Timestamp when the request was initiated.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Indicates whether this call was streamed.
    /// </summary>
    public bool IsStreaming { get; init; }

    /// <summary>
    /// Indicates whether the AI invocation succeeded.
    /// </summary>
    public bool Success { get; init; } = true;

    /// <summary>
    /// Error message if the request failed.
    /// </summary>
    public string? ErrorMessage { get; init; }

    /// <summary>
    /// Error type name if the request failed.
    /// </summary>
    public string? ErrorType { get; init; }

    /// <summary>
    /// Optional tenant identifier for multi-tenant apps.
    /// </summary>
    public string? TenantId { get; init; }

    /// <summary>
    /// Optional user identifier.
    /// </summary>
    public string? UserId { get; init; }

    /// <summary>
    /// Optional operation or scenario name (e.g., "rag_query", "agent_step").
    /// </summary>
    public string? Operation { get; init; }

    /// <summary>
    /// The original prompt text sent to the model (if captured).
    /// </summary>
    public string? Prompt { get; init; }

    /// <summary>
    /// The textual response generated by the model (if captured).
    /// </summary>
    public string? ResponseText { get; init; }

    /// <summary>
    /// Function and tool calls executed during this invocation.
    /// </summary>
    public IReadOnlyList<ToolInvocationRecord> ToolInvocations { get; init; } = Array.Empty<ToolInvocationRecord>();

    /// <summary>
    /// Model Context Protocol (MCP) server calls and resources accessed.
    /// </summary>
    public IReadOnlyList<McpInvocationRecord> McpInvocations { get; init; } = Array.Empty<McpInvocationRecord>();

    /// <summary>
    /// Subagents delegated to during this invocation.
    /// </summary>
    public IReadOnlyList<SubagentInvocationRecord> SubagentInvocations { get; init; } = Array.Empty<SubagentInvocationRecord>();

    /// <summary>
    /// Evaluated assertions and their pass/fail outcomes.
    /// </summary>
    public IReadOnlyList<AssertionResult> Assertions { get; init; } = Array.Empty<AssertionResult>();

    /// <summary>
    /// Custom metadata tags attached to the execution.
    /// </summary>
    public IReadOnlyDictionary<string, object?> Tags { get; init; } = new Dictionary<string, object?>();
}
